name: esp-make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get ESP-IDF SDK and compile project
        run: |
          cd ../
          git clone https://github.com/espressif/esp-idf.git
          cd esp-idf
          git checkout release/v4.4
          ./install.sh
          . ./export.sh
          cd ../esp32-keyboard
          idf.py reconfigure build
